{
 "title": "Ojo Metrics",
 "tags": [
  "otel",
  "prometheus",
  "procfs",
  "host",
  "process"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(system_cpu_utilization, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(system_cpu_utilization{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "device",
    "label": "device",
    "query": {
     "query": "label_values(system_disk_io{job=~\"$job\",instance=~\"$instance\"}, device)"
    }
   },
   {
    "name": "cpu",
    "label": "cpu",
    "query": {
     "query": "label_values(system_cpu_core_utilization{job=~\"$job\",instance=~\"$instance\"}, cpu)"
    }
   },
   {
    "name": "net_device",
    "label": "net device",
    "query": {
     "query": "label_values(system_network_rx_packets{job=~\"$job\",instance=~\"$instance\"}, device)"
    }
   },
   {
    "name": "pid",
    "label": "pid",
    "query": {
     "query": "label_values(process_cpu_utilization{job=~\"$job\",instance=~\"$instance\"}, pid)"
    }
   },
   {
    "name": "comm",
    "label": "comm",
    "query": {
     "query": "label_values(process_cpu_utilization{job=~\"$job\",instance=~\"$instance\",pid=~\"$pid\"}, comm)"
    }
   },
   {
    "name": "key",
    "label": "key",
    "query": {
     "query": "label_values(system_linux_vmstat{job=~\"$job\",instance=~\"$instance\"}, key)"
    }
   },
   {
    "name": "snmp_key",
    "label": "snmp key",
    "query": {
     "query": "label_values(system_linux_net_snmp{job=~\"$job\",instance=~\"$instance\"}, key)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "clamp_min(rate(process_context_switches_total{job=~\"$job\",instance=~\"$instance\",pid=~\"$pid\",comm=~\"$comm\"}[5m]), 0)",
     "legendFormat": "pid={{pid}} comm={{comm}} {{type}}"
    }
   ]
  },
  {
   "title": "Process Cpu Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamp_min(rate(process_cpu_time_seconds_total{job=~\"$job\",instance=~\"$instance\",pid=~\"$pid\",comm=~\"$comm\"}[5m]), 0)",
     "legendFormat": "pid={{pid}} comm={{comm}} {{state}}"
    }
   ]
  },
  {
   "title": "Process Cpu Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_utilization{job=~\"$job\",instance=~\"$instance\",pid=~\"$pid\",comm=~\"$comm\"}",
     "legendFormat": "pid={{pid}} comm={{comm}}"
    }
   ]
  },
  {
   "title": "Process Disk Io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "clamp_min(rate(process_disk_io_bytes_total{job=~\"$job\",instance=~\"$instance\",pid=~\"$pid\",comm=~\"$comm\"}[5m]), 0)",
     "legendFormat": "pid={{pid}} comm={{comm}} {{direction}}"
    }
   ]
  },
  {
   "title": "Process Io Cancelled Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "process_linux_io_cancelled_write_bytes{job=~\"$job\",instance=~\"$instance\",pid=~\"$pid\",comm=~\"$comm\"}",
     "legendFormat": "pid={{pid}} comm={{comm}}"
    }
   ]
  },
  {
   "title": "Process Io Chars",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "clamp_min(rate(process_io_chars_bytes_total{job=~\"$job\",instance=~\"$instance\",pid=~\"$pid\",comm=~\"$comm\"}[5m]), 0)",
     "legendFormat": "pid={{pid}} comm={{comm}} {{direction}}"
    }
   ]
  },
  {
   "title": "Process Io Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "clamp_min(deriv(process_io_read_bytes{job=~\"$job\",instance=~\"$instance\",pid=~\"$pid\",comm=~\"$comm\"}[5m]), 0)",
     "legendFormat": "pid={{pid}} comm={{comm}}"
    }
   ]
  }
 ]
}