server:
  http_listen_port: 3200

multitenancy_enabled: true

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 48h

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://mimir:9009/api/v1/push
        headers:
          X-Scope-OrgID: ${MIMIR_TENANT_ID}
        send_exemplars: true

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

overrides:
  max_search_duration: 168h
  max_bytes_per_trace: 5000000    
  ingestion_rate_limit_bytes: 5000000 
  ingestion_burst_size_bytes: 10000000
  max_traces_per_user: 20000
  metrics_generator_processors: [service-graphs, span-metrics]